import Head from 'next/head'
import React from 'react'
import Bar from './Bar'
import Footer from './Footer'
import Navbar from './Navbar'
import Sidebar from './Sidebar'

interface Props{
    children: any
}


const Layout = ({ children }: Props) => {
  return (
    <div className='layout overflow-x-hidden'>
        <Head>
        <title>Air man 23</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" type="image/png" href="/fireball.png" />
      </Head>

      <header>
        <Navbar/>
      </header>

     <div className='flex'>
     <section>
      <Sidebar/>
     </section>

      <main>
        {children}
      </main>
     </div>
  

     <div>
      <Bar/>
     </div>

      <footer>
        <Footer/>
      </footer>
    </div>
  )
}

export default Layout