import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className='bg-[var(--bg-dark)] w-screen h-screen' > 

          <h1 className='gradient text-white font-bold w-20 p-4'>hola</h1>
     
        </div>
      </main>
    </>
  )
}
