import Head from 'next/head'
import Categories from '../components/Categories';
import Feed from '../components/Feed';
import { client } from '../lib/client';


interface Props {
  posts: any

}

export default function Home({posts}: Props) {
  return (
    <>
      <Head>
        <title>Descry | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className='bg-[var(--bg-dark)] w-screen h-screen' > 

        {/**categories */}

       <div className='w-[95vw] mx-auto'>
       <Categories/>
       </div>

        {/**feed */}

        <div className='grid grid-cols-2 gap-2 w-[95vw] mx-auto'>
          {posts?.map((post: any) => (
            <Feed post={post} key={post._id} image={undefined}/>
          ))}
        </div>

        </div>
      </main>
    </>
  )
}


//server side props

export const getServerSideProps = async () => {

  const postQuery = '*[_type == "post"]';
  const posts = await client.fetch(postQuery);

  return {
   props: { posts }
  }
 
 }